// resources/js/vue3/components/Checkbox.vue
<template>
    <div class="p-12">
        <div>
            <ui-checkbox sm v-model="check" label="Foo" />
            <ui-checkbox sm v-model="check" blue> Bar </ui-checkbox>
            <ui-checkbox sm v-model="check" green> Baz </ui-checkbox>
            <ui-checkbox sm v-model="check" red> Boom </ui-checkbox>
            <ui-checkbox sm v-model="check" yellow> Foo </ui-checkbox>
            <ui-checkbox sm v-model="check" gray> Foo </ui-checkbox>
        </div>
        <div>
            <ui-checkbox v-model="check" label="Foo" />
            <ui-checkbox v-model="check" blue> Foo </ui-checkbox>
            <ui-checkbox v-model="check" green> Foo </ui-checkbox>
            <ui-checkbox v-model="check" red> Foo </ui-checkbox>
            <ui-checkbox v-model="check" yellow> Foo </ui-checkbox>
            <ui-checkbox v-model="check" gray> Foo </ui-checkbox>
        </div>
        <div>
            <ui-checkbox size="lg" v-model="check" label="Foo" />
            <ui-checkbox lg v-model="check" blue> Foo </ui-checkbox>
            <ui-checkbox lg v-model="check" green> Foo </ui-checkbox>
            <ui-checkbox lg v-model="check" red> Foo </ui-checkbox>
            <ui-checkbox lg v-model="check" yellow> Foo </ui-checkbox>
            <ui-checkbox lg v-model="check" gray> Foo </ui-checkbox>
        </div>
        Checked: {{ check }}
    </div>
</template>

<script>
import { defineComponent, ref } from 'vue';
export default defineComponent({
    setup() {
        const check = ref(true);

        return {
            check,
        };
    },
});
</script>

// resources/js/react/components/Checkbox.tsx
import { useState } from 'react';
// import { Checkbox } from '@macramejs/admin-react';

export default function() {
    let [checked, setChecked] = useState<boolean>(false);
    return (
        <div className="p-24 w-full h-full fixed bg-gray-100 gap-5">
            <div className="flex mb-5 space-x-5">
                {/* <Checkbox checked={checked} onChange={setChecked} yellow sm> Foo </Checkbox>
                <Checkbox checked={checked} onChange={setChecked} green md> Bar </Checkbox>
                <Checkbox checked={checked} onChange={setChecked} blue lg> Baz </Checkbox>
            </div>
            <div className="flex mb-5 space-x-5">
                <Checkbox checked={checked} onChange={setChecked} variant="red" size="sm" label="Foo" />
                <Checkbox checked={checked} onChange={setChecked} size="md" label="Bar" />
                <Checkbox checked={checked} onChange={setChecked} size="lg" label="Baz" /> */}
            </div>
        </div>
    );
}
