// resources/js/vue3/components/Dropdown.vue
<template>
    <div class="p-4">
        <div class="flex justify-between">
            <ui-dropdown text="Toggle me" left>
                <ui-dropdown-item>Hello</ui-dropdown-item>
                <ui-dropdown-item href="/">Hello</ui-dropdown-item>
            </ui-dropdown>
            <ui-dropdown right>
                <template v-slot:button>
                    <ui-button>Right</ui-button>
                </template>

                <ui-dropdown-group title="Group A">
                    <ui-dropdown-item>Foo</ui-dropdown-item>
                    <ui-dropdown-item>Bar</ui-dropdown-item>
                </ui-dropdown-group>
                <ui-dropdown-divider />
                <ui-dropdown-group>
                    <template v-slot:title> Group B </template>
                    <ui-dropdown-item>Baz</ui-dropdown-item>
                    <ui-dropdown-item>Boom</ui-dropdown-item>
                </ui-dropdown-group>
            </ui-dropdown>
        </div>
    </div>
</template>

<script>
import { defineComponent } from 'vue';

export default defineComponent({
    setup() {
        //
    },
});
</script>

// resources/js/react/components/Dropdown.tsx
import { Dropdown, Button } from '@macramejs/admin-react';

export default function() {
    return (
        <div className="p-24 w-full h-full fixed bg-gray-700 flex flex-wrap gap-5">
            <Dropdown text="Toggle me" left>
                <Dropdown.Item>Hello</Dropdown.Item>
                <Dropdown.Item href="/">Hello</Dropdown.Item>
            </Dropdown>
            <Dropdown right text={
                <Button>Right</Button>
            }>
                <Dropdown.Group title="Group A">
                    <Dropdown.Item>Foo</Dropdown.Item>
                    <Dropdown.Item>Bar</Dropdown.Item>
                </Dropdown.Group>
                <Dropdown.Divider />
                <Dropdown.Group title={'Group B'}>
                    <Dropdown.Item>Baz</Dropdown.Item>
                    <Dropdown.Item>Boom</Dropdown.Item>
                </Dropdown.Group>
            </Dropdown>
        </div>
    );
}
