// resources/js/react/components/Toggle.tsx
import { useState } from 'react';
import { Toggle } from '@macramejs/admin-react';

export default function() {
    let [checked, setChecked] = useState<boolean>(false);
    return (
        <div className="p-24 w-full h-full fixed bg-gray-100 gap-5">
            <div className="flex mb-5 space-x-5">
                <Toggle checked={checked} onChange={setChecked} yellow sm> Foo </Toggle>
                <Toggle checked={checked} onChange={setChecked} green md> Bar </Toggle>
                <Toggle checked={checked} onChange={setChecked} blue lg> Baz </Toggle>
            </div>
            <div className="flex mb-5 space-x-5">
                <Toggle checked={checked} onChange={setChecked} variant="red" size="sm" label="Foo" />
                <Toggle checked={checked} onChange={setChecked} size="md" label="Bar" />
                <Toggle checked={checked} onChange={setChecked} size="lg" label="Baz" />
            </div>
        </div>
    );
}

// resources/js/vue3/components/Toggle.vue
<template>
    <div class="p-24">
        <div class="flex mb-5 space-x-5">
            <ui-toggle v-model="toggle" yellow sm> Foo </ui-toggle>
            <ui-toggle v-model="toggle" green md> Bar </ui-toggle>
            <ui-toggle v-model="toggle" blue lg> Baz </ui-toggle>
        </div>
        <div class="flex mb-5 space-x-5">
            <ui-toggle v-model="toggle" variant="red" size="sm" label="Foo" />
            <ui-toggle v-model="toggle" size="md" label="Bar" />
            <ui-toggle v-model="toggle" size="lg" label="Baz" />
        </div>
        {{ toggle }}
    </div>
</template>

<script>
import { defineComponent, ref } from 'vue';
export default defineComponent({
    setup() {
        const toggle = ref(false);
        return {
            toggle,
        };
    },
});
</script>
